import Link from "next/link";
import { deletePost, logout, savePost } from "@/app/admin/actions";
import { requireEditor } from "@/lib/auth";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export const dynamic = "force-dynamic";

export default async function AdminPage() {
  const actor = await requireEditor(); const db = createSupabaseAdminClient();
  const { data: posts } = await db!.from("posts").select("id,slug,title,type,status,published_at,updated_at").order("updated_at", { ascending: false }).limit(100);
  const { data: runs } = await db!.from("processing_runs").select("id,kind,status,started_at,finished_at,error_message").order("started_at", { ascending: false }).limit(8);
  return <main className="admin-shell"><header className="admin-header"><Link className="brand" href="/"><span>PROSPECTA</span><b>4.0</b></Link><span>Painel de gestão</span><div><small>{actor.user.email} · {actor.role}</small><form action={logout}><button>Sair</button></form></div></header><section className="admin-content"><div className="admin-title"><div><div className="eyebrow">Conteúdo</div><h1>Central editorial.</h1></div><a className="button" href="#novo-post">Nova publicação</a></div><div className="admin-grid"><section className="admin-panel"><h2>Publicações</h2><div className="admin-list">{posts?.map((post) => <div key={post.id}><div><strong>{post.title}</strong><small>{post.type} · {post.status} · {post.published_at ? new Date(post.published_at).toLocaleDateString("pt-BR") : "sem publicação"}</small></div><div><Link href={`/blog/${post.slug}`}>Ver</Link>{actor.role === "admin" && <form action={deletePost}><input type="hidden" name="id" value={post.id}/><button className="danger">Excluir</button></form>}</div></div>)}{!posts?.length && <p>Nenhum conteúdo cadastrado.</p>}</div></section><section className="admin-panel"><h2>Processamentos recentes</h2><div className="admin-list">{runs?.map((run) => <div key={run.id}><div><strong>{run.kind}</strong><small>{new Date(run.started_at).toLocaleString("pt-BR")}</small></div><span className={`status ${run.status}`}>{run.status}</span></div>)}{!runs?.length && <p>A pipeline ainda não foi executada.</p>}</div></section></div><section className="admin-panel editor" id="novo-post"><h2>Nova publicação</h2><form action={savePost} className="editor-form"><label>Título<input name="title" required minLength={8}/></label><label>Slug<input name="slug" required pattern="[a-z0-9-]+" placeholder="titulo-da-publicacao"/></label><label>Tipo<select name="type"><option value="noticia">Notícia</option><option value="publicacao">Publicação</option></select></label><label>Status<select name="status"><option value="draft">Rascunho</option><option value="review">Em revisão</option><option value="scheduled">Agendado</option><option value="published">Publicado</option></select></label><label>Fonte<input name="source" required/></label><label>Referência<input name="reference"/></label><label className="full">Resumo<textarea name="excerpt" required minLength={20} rows={3}/></label><label className="full">Conteúdo<textarea name="body" required minLength={30} rows={12}/></label><label className="full">Autores<input name="authors"/></label><label>Tags separadas por vírgula<input name="tags"/></label><label>Data de publicação<input name="published_at" type="datetime-local"/></label><label className="full">URL da capa<input name="cover_url" type="url"/></label><div className="full"><button className="button">Salvar conteúdo</button></div></form></section></section></main>;
}
